#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor HDMI-1 -d X
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         5
bspc config window_gap           10
##  bspc config active_border_color '#aa00aa'
##  bspc config normal_border_color '#552055'
##  bspc config focused_border_color '#ff33ac'
bspc config active_border_color '#00ffff'
bspc config normal_border_color '#2288ff'
bspc config focused_border_color '#00ffff'

bspc config split_ratio          0.56
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
bspc rule -a Quodlibet desktop='^9'
bspc rule -a Telegram desktop='^8'
bspc rule -a Nautilus desktop='^7'
bspc rule -a Firefox desktop='^3'
bspc rule -a Code desktop='^1'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-scale /home/dv/Pictures/wallpapers/mountain.jpg
killall picom ; picom
killall polybar ; sleep 2; bash ~/.config/polybar/launch.sh --blocks
flameshot
xmodmap /home/dv/.Xmodmap
#killall redshift ; sleep 2; redshift -l -18:-48 -t 5700:3100 -b 100:100
#killall dunst ; dunst
wmname LG3D
xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-1 --mode 1920x1080 --rotate normal --same-as eDP-1
