#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor HDMI-1 -d X
bspc monitor -d I II III IV V VI VII VIII IX X

#bspc config initial_polarity first_child # inverte novo
bspc config border_width         4
bspc config window_gap           0
##  bspc config active_border_color '#aa00aa'
##  bspc config normal_border_color '#552055'
##  bspc config focused_border_color '#ff33ac'
##  bspc config active_border_color '#aa0000'
##  bspc config normal_border_color '#ff3333'
##  bspc config focused_border_color '#FFb010'
#### tealized
##bspc config active_border_color '#00aacc'
##bspc config normal_border_color '#0055aa'
##bspc config focused_border_color '#00aacc'
#### CYBERPUNK
bspc config active_border_color '#00ffff'
bspc config normal_border_color '#339933'
bspc config focused_border_color '#ff44ff'

bspc config split_ratio          0.56
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
bspc rule -a Quodlibet desktop='^9'
bspc rule -a Telegram desktop='^8'
bspc rule -a Firefox desktop='^3'
bspc rule -a Code desktop='^1'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura manage=on state=tiling

xmodmap /home/workdv/.Xmodmap
wmname LG3D
flameshot
feh --bg-scale /home/workdv/Pictures/wallpapers/cyberpunk/vice_city.jpg &
killall picom ; sleep 2 ; picom -b &
killall polybar ; sleep 2 ; bash ~/.config/polybar/launch.sh --cuts &
killall dunst ; sleep 2 ; dunst &
#killall redshift ; sleep 5; redshift -l -18:-48 -t 6500:2800 -b 1:1 &
#killall conky ; conky &
